sudo: required
services:
  - docker

before_install:
  - docker build -t idks/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true idks/docker-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-492817457150"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
